<?php
/**
 * RoutesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Samsara API
 *
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RoutesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoutesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDispatchRoute
     *
     * /fleet/dispatch/routes.
     *
     */
    public function testCreateDispatchRoute()
    {
    }

    /**
     * Test case for createDriverDispatchRoute
     *
     * /fleet/drivers/{driver_id:[0-9]+}/dispatch/routes.
     *
     */
    public function testCreateDriverDispatchRoute()
    {
    }

    /**
     * Test case for createVehicleDispatchRoute
     *
     * /fleet/vehicles/{vehicle_id:[0-9]+}/dispatch/routes.
     *
     */
    public function testCreateVehicleDispatchRoute()
    {
    }

    /**
     * Test case for deleteDispatchRouteById
     *
     * /fleet/dispatch/routes/{route_id:[0-9]+}/.
     *
     */
    public function testDeleteDispatchRouteById()
    {
    }

    /**
     * Test case for fetchAllDispatchRoutes
     *
     * /fleet/dispatch/routes.
     *
     */
    public function testFetchAllDispatchRoutes()
    {
    }

    /**
     * Test case for getDispatchRouteById
     *
     * /fleet/dispatch/routes/{route_id:[0-9]+}.
     *
     */
    public function testGetDispatchRouteById()
    {
    }

    /**
     * Test case for getDispatchRouteHistory
     *
     * /fleet/dispatch/routes/{route_id:[0-9]+}/history.
     *
     */
    public function testGetDispatchRouteHistory()
    {
    }

    /**
     * Test case for getDispatchRoutesByDriverId
     *
     * /fleet/drivers/{driver_id:[0-9]+}/dispatch/routes.
     *
     */
    public function testGetDispatchRoutesByDriverId()
    {
    }

    /**
     * Test case for getDispatchRoutesByVehicleId
     *
     * /fleet/vehicles/{vehicle_id:[0-9]+}/dispatch/routes.
     *
     */
    public function testGetDispatchRoutesByVehicleId()
    {
    }

    /**
     * Test case for updateDispatchRouteById
     *
     * /fleet/dispatch/routes/{route_id:[0-9]+}/.
     *
     */
    public function testUpdateDispatchRouteById()
    {
    }
}
