<?php
/**
 * DriverDailyLogResponseSummaries
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Samsara API
 *
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\models;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DriverDailyLogResponseSummaries Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DriverDailyLogResponseSummaries implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DriverDailyLogResponse_summaries';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'active_hours' => 'float',
        'certified' => 'bool',
        'certified_at_ms' => 'float',
        'distance_miles' => 'float',
        'start_ms' => 'int',
        'end_ms' => 'int',
        'trailer_ids' => 'object',
        'vehicle_ids' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'active_hours' => 'float',
        'certified' => null,
        'certified_at_ms' => 'int64',
        'distance_miles' => 'float',
        'start_ms' => null,
        'end_ms' => null,
        'trailer_ids' => null,
        'vehicle_ids' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'active_hours' => 'activeHours',
        'certified' => 'certified',
        'certified_at_ms' => 'certifiedAtMs',
        'distance_miles' => 'distanceMiles',
        'start_ms' => 'startMs',
        'end_ms' => 'endMs',
        'trailer_ids' => 'trailerIds',
        'vehicle_ids' => 'vehicleIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'active_hours' => 'setActiveHours',
        'certified' => 'setCertified',
        'certified_at_ms' => 'setCertifiedAtMs',
        'distance_miles' => 'setDistanceMiles',
        'start_ms' => 'setStartMs',
        'end_ms' => 'setEndMs',
        'trailer_ids' => 'setTrailerIds',
        'vehicle_ids' => 'setVehicleIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'active_hours' => 'getActiveHours',
        'certified' => 'getCertified',
        'certified_at_ms' => 'getCertifiedAtMs',
        'distance_miles' => 'getDistanceMiles',
        'start_ms' => 'getStartMs',
        'end_ms' => 'getEndMs',
        'trailer_ids' => 'getTrailerIds',
        'vehicle_ids' => 'getVehicleIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['active_hours'] = isset($data['active_hours']) ? $data['active_hours'] : null;
        $this->container['certified'] = isset($data['certified']) ? $data['certified'] : null;
        $this->container['certified_at_ms'] = isset($data['certified_at_ms']) ? $data['certified_at_ms'] : null;
        $this->container['distance_miles'] = isset($data['distance_miles']) ? $data['distance_miles'] : null;
        $this->container['start_ms'] = isset($data['start_ms']) ? $data['start_ms'] : null;
        $this->container['end_ms'] = isset($data['end_ms']) ? $data['end_ms'] : null;
        $this->container['trailer_ids'] = isset($data['trailer_ids']) ? $data['trailer_ids'] : null;
        $this->container['vehicle_ids'] = isset($data['vehicle_ids']) ? $data['vehicle_ids'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets active_hours
     *
     * @return float
     */
    public function getActiveHours()
    {
        return $this->container['active_hours'];
    }

    /**
     * Sets active_hours
     *
     * @param float $active_hours Hours spent on duty or driving, rounded to two decimal places.
     *
     * @return $this
     */
    public function setActiveHours($active_hours)
    {
        $this->container['active_hours'] = $active_hours;

        return $this;
    }

    /**
     * Gets certified
     *
     * @return bool
     */
    public function getCertified()
    {
        return $this->container['certified'];
    }

    /**
     * Sets certified
     *
     * @param bool $certified Whether this HOS day chart was certified by the driver.
     *
     * @return $this
     */
    public function setCertified($certified)
    {
        $this->container['certified'] = $certified;

        return $this;
    }

    /**
     * Gets certified_at_ms
     *
     * @return float
     */
    public function getCertifiedAtMs()
    {
        return $this->container['certified_at_ms'];
    }

    /**
     * Sets certified_at_ms
     *
     * @param float $certified_at_ms Unix epoch time (in ms) of time when this chart was certified. If this chart is uncertified, 0.
     *
     * @return $this
     */
    public function setCertifiedAtMs($certified_at_ms)
    {
        $this->container['certified_at_ms'] = $certified_at_ms;

        return $this;
    }

    /**
     * Gets distance_miles
     *
     * @return float
     */
    public function getDistanceMiles()
    {
        return $this->container['distance_miles'];
    }

    /**
     * Sets distance_miles
     *
     * @param float $distance_miles Distance driven in miles, rounded to two decimal places.
     *
     * @return $this
     */
    public function setDistanceMiles($distance_miles)
    {
        $this->container['distance_miles'] = $distance_miles;

        return $this;
    }

    /**
     * Gets start_ms
     *
     * @return int
     */
    public function getStartMs()
    {
        return $this->container['start_ms'];
    }

    /**
     * Sets start_ms
     *
     * @param int $start_ms End of the HOS day, specified in milliseconds UNIX time.
     *
     * @return $this
     */
    public function setStartMs($start_ms)
    {
        $this->container['start_ms'] = $start_ms;

        return $this;
    }

    /**
     * Gets end_ms
     *
     * @return int
     */
    public function getEndMs()
    {
        return $this->container['end_ms'];
    }

    /**
     * Sets end_ms
     *
     * @param int $end_ms End of the HOS day, specified in milliseconds UNIX time.
     *
     * @return $this
     */
    public function setEndMs($end_ms)
    {
        $this->container['end_ms'] = $end_ms;

        return $this;
    }

    /**
     * Gets trailer_ids
     *
     * @return object
     */
    public function getTrailerIds()
    {
        return $this->container['trailer_ids'];
    }

    /**
     * Sets trailer_ids
     *
     * @param object $trailer_ids List of trailer ID's associated with the driver for the day.
     *
     * @return $this
     */
    public function setTrailerIds($trailer_ids)
    {
        $this->container['trailer_ids'] = $trailer_ids;

        return $this;
    }

    /**
     * Gets vehicle_ids
     *
     * @return object
     */
    public function getVehicleIds()
    {
        return $this->container['vehicle_ids'];
    }

    /**
     * Sets vehicle_ids
     *
     * @param object $vehicle_ids List of vehicle ID's associated with the driver for the day.
     *
     * @return $this
     */
    public function setVehicleIds($vehicle_ids)
    {
        $this->container['vehicle_ids'] = $vehicle_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

