<?php
/**
 * HistoryParam
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Samsara API
 *
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\models;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * HistoryParam Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoryParam implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'historyParam';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'group_id' => 'int',
        'start_ms' => 'int',
        'end_ms' => 'int',
        'step_ms' => 'int',
        'series' => '\Swagger\Client\models\SensorshistorySeries[]',
        'fill_missing' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'group_id' => 'int64',
        'start_ms' => null,
        'end_ms' => null,
        'step_ms' => null,
        'series' => null,
        'fill_missing' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'group_id' => 'groupId',
        'start_ms' => 'startMs',
        'end_ms' => 'endMs',
        'step_ms' => 'stepMs',
        'series' => 'series',
        'fill_missing' => 'fillMissing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'group_id' => 'setGroupId',
        'start_ms' => 'setStartMs',
        'end_ms' => 'setEndMs',
        'step_ms' => 'setStepMs',
        'series' => 'setSeries',
        'fill_missing' => 'setFillMissing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'group_id' => 'getGroupId',
        'start_ms' => 'getStartMs',
        'end_ms' => 'getEndMs',
        'step_ms' => 'getStepMs',
        'series' => 'getSeries',
        'fill_missing' => 'getFillMissing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const FILL_MISSING_WITH_NULL = 'withNull';
    const FILL_MISSING_WITH_PREVIOUS = 'withPrevious';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFillMissingAllowableValues()
    {
        return [
            self::FILL_MISSING_WITH_NULL,
            self::FILL_MISSING_WITH_PREVIOUS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['group_id'] = isset($data['group_id']) ? $data['group_id'] : null;
        $this->container['start_ms'] = isset($data['start_ms']) ? $data['start_ms'] : null;
        $this->container['end_ms'] = isset($data['end_ms']) ? $data['end_ms'] : null;
        $this->container['step_ms'] = isset($data['step_ms']) ? $data['step_ms'] : null;
        $this->container['series'] = isset($data['series']) ? $data['series'] : null;
        $this->container['fill_missing'] = isset($data['fill_missing']) ? $data['fill_missing'] : 'withNull';
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['group_id'] === null) {
            $invalidProperties[] = "'group_id' can't be null";
        }
        if ($this->container['start_ms'] === null) {
            $invalidProperties[] = "'start_ms' can't be null";
        }
        if ($this->container['end_ms'] === null) {
            $invalidProperties[] = "'end_ms' can't be null";
        }
        if ($this->container['step_ms'] === null) {
            $invalidProperties[] = "'step_ms' can't be null";
        }
        if ($this->container['series'] === null) {
            $invalidProperties[] = "'series' can't be null";
        }
        $allowedValues = $this->getFillMissingAllowableValues();
        if (!in_array($this->container['fill_missing'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'fill_missing', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['group_id'] === null) {
            return false;
        }
        if ($this->container['start_ms'] === null) {
            return false;
        }
        if ($this->container['end_ms'] === null) {
            return false;
        }
        if ($this->container['step_ms'] === null) {
            return false;
        }
        if ($this->container['series'] === null) {
            return false;
        }
        $allowedValues = $this->getFillMissingAllowableValues();
        if (!in_array($this->container['fill_missing'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets group_id
     *
     * @return int
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param int $group_id Group ID to query.
     *
     * @return $this
     */
    public function setGroupId($group_id)
    {
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets start_ms
     *
     * @return int
     */
    public function getStartMs()
    {
        return $this->container['start_ms'];
    }

    /**
     * Sets start_ms
     *
     * @param int $start_ms Beginning of the time range, specified in milliseconds UNIX time.
     *
     * @return $this
     */
    public function setStartMs($start_ms)
    {
        $this->container['start_ms'] = $start_ms;

        return $this;
    }

    /**
     * Gets end_ms
     *
     * @return int
     */
    public function getEndMs()
    {
        return $this->container['end_ms'];
    }

    /**
     * Sets end_ms
     *
     * @param int $end_ms End of the time range, specified in milliseconds UNIX time.
     *
     * @return $this
     */
    public function setEndMs($end_ms)
    {
        $this->container['end_ms'] = $end_ms;

        return $this;
    }

    /**
     * Gets step_ms
     *
     * @return int
     */
    public function getStepMs()
    {
        return $this->container['step_ms'];
    }

    /**
     * Sets step_ms
     *
     * @param int $step_ms Time resolution for which data should be returned, in milliseconds. Specifying 3600000 will return data at hour intervals.
     *
     * @return $this
     */
    public function setStepMs($step_ms)
    {
        $this->container['step_ms'] = $step_ms;

        return $this;
    }

    /**
     * Gets series
     *
     * @return \Swagger\Client\models\SensorshistorySeries[]
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param \Swagger\Client\models\SensorshistorySeries[] $series series
     *
     * @return $this
     */
    public function setSeries($series)
    {
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets fill_missing
     *
     * @return string
     */
    public function getFillMissing()
    {
        return $this->container['fill_missing'];
    }

    /**
     * Sets fill_missing
     *
     * @param string $fill_missing fill_missing
     *
     * @return $this
     */
    public function setFillMissing($fill_missing)
    {
        $allowedValues = $this->getFillMissingAllowableValues();
        if (!is_null($fill_missing) && !in_array($fill_missing, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'fill_missing', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fill_missing'] = $fill_missing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

