<?php
/**
 * DispatchJobCreate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Samsara API
 *
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DispatchJobCreate Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DispatchJobCreate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DispatchJobCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'scheduled_arrival_time_ms' => 'int',
        'notes' => 'string',
        'destination_name' => 'string',
        'destination_address' => 'string',
        'destination_lat' => 'float',
        'destination_lng' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'scheduled_arrival_time_ms' => 'int64',
        'notes' => null,
        'destination_name' => null,
        'destination_address' => null,
        'destination_lat' => 'float',
        'destination_lng' => 'float'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'scheduled_arrival_time_ms' => 'scheduled_arrival_time_ms',
        'notes' => 'notes',
        'destination_name' => 'destination_name',
        'destination_address' => 'destination_address',
        'destination_lat' => 'destination_lat',
        'destination_lng' => 'destination_lng'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'scheduled_arrival_time_ms' => 'setScheduledArrivalTimeMs',
        'notes' => 'setNotes',
        'destination_name' => 'setDestinationName',
        'destination_address' => 'setDestinationAddress',
        'destination_lat' => 'setDestinationLat',
        'destination_lng' => 'setDestinationLng'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'scheduled_arrival_time_ms' => 'getScheduledArrivalTimeMs',
        'notes' => 'getNotes',
        'destination_name' => 'getDestinationName',
        'destination_address' => 'getDestinationAddress',
        'destination_lat' => 'getDestinationLat',
        'destination_lng' => 'getDestinationLng'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['scheduled_arrival_time_ms'] = isset($data['scheduled_arrival_time_ms']) ? $data['scheduled_arrival_time_ms'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['destination_name'] = isset($data['destination_name']) ? $data['destination_name'] : null;
        $this->container['destination_address'] = isset($data['destination_address']) ? $data['destination_address'] : null;
        $this->container['destination_lat'] = isset($data['destination_lat']) ? $data['destination_lat'] : null;
        $this->container['destination_lng'] = isset($data['destination_lng']) ? $data['destination_lng'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['scheduled_arrival_time_ms'] === null) {
            $invalidProperties[] = "'scheduled_arrival_time_ms' can't be null";
        }
        if ($this->container['destination_lat'] === null) {
            $invalidProperties[] = "'destination_lat' can't be null";
        }
        if ($this->container['destination_lng'] === null) {
            $invalidProperties[] = "'destination_lng' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['scheduled_arrival_time_ms'] === null) {
            return false;
        }
        if ($this->container['destination_lat'] === null) {
            return false;
        }
        if ($this->container['destination_lng'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets scheduled_arrival_time_ms
     *
     * @return int
     */
    public function getScheduledArrivalTimeMs()
    {
        return $this->container['scheduled_arrival_time_ms'];
    }

    /**
     * Sets scheduled_arrival_time_ms
     *
     * @param int $scheduled_arrival_time_ms The time at which the assigned driver is scheduled to arrive at the job destination.
     *
     * @return $this
     */
    public function setScheduledArrivalTimeMs($scheduled_arrival_time_ms)
    {
        $this->container['scheduled_arrival_time_ms'] = $scheduled_arrival_time_ms;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string $notes Notes regarding the details of this job.
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets destination_name
     *
     * @return string
     */
    public function getDestinationName()
    {
        return $this->container['destination_name'];
    }

    /**
     * Sets destination_name
     *
     * @param string $destination_name The name of the job destination.
     *
     * @return $this
     */
    public function setDestinationName($destination_name)
    {
        $this->container['destination_name'] = $destination_name;

        return $this;
    }

    /**
     * Gets destination_address
     *
     * @return string
     */
    public function getDestinationAddress()
    {
        return $this->container['destination_address'];
    }

    /**
     * Sets destination_address
     *
     * @param string $destination_address The address of the job destination, as it would be recognized if provided to maps.google.com
     *
     * @return $this
     */
    public function setDestinationAddress($destination_address)
    {
        $this->container['destination_address'] = $destination_address;

        return $this;
    }

    /**
     * Gets destination_lat
     *
     * @return float
     */
    public function getDestinationLat()
    {
        return $this->container['destination_lat'];
    }

    /**
     * Sets destination_lat
     *
     * @param float $destination_lat Latitude of the destination in decimal degrees.
     *
     * @return $this
     */
    public function setDestinationLat($destination_lat)
    {
        $this->container['destination_lat'] = $destination_lat;

        return $this;
    }

    /**
     * Gets destination_lng
     *
     * @return float
     */
    public function getDestinationLng()
    {
        return $this->container['destination_lng'];
    }

    /**
     * Sets destination_lng
     *
     * @param float $destination_lng Latitude of the destination in decimal degrees.
     *
     * @return $this
     */
    public function setDestinationLng($destination_lng)
    {
        $this->container['destination_lng'] = $destination_lng;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

