<?php
/**
 * VehicleMaintenanceJ1939DiagnosticTroubleCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Samsara API
 *
 * # Introduction The Samsara REST API lets you interact with the Samsara Cloud from anything that can send an HTTP request. With the Samsara API you can build powerful applications and custom solutions with sensor data.  Samsara has endpoints available to track and analyze sensors, vehicles, and entire fleets. If you’re familiar with what you can build with a REST API, the following API reference guide will be your go-to resource.  API access to the Samsara cloud is available to all Samsara administrators. If you’d like to try the API, [contact us](https://www.samsara.com/free-trial). The API is currently in beta and may be subject to frequent changes.  # Connecting to the API There are two ways to connect to the API. If you prefer to use the API in Javascript or Python, we supply SDKs which you can download here: [Javascript SDK](https://github.com/samsarahq/samsara-js), [Python SDK](https://github.com/samsarahq/samsara-python).  If you’d rather use another language to interact with the Samsara API, the endpoints and examples are in the reference guide below.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * VehicleMaintenanceJ1939DiagnosticTroubleCodes Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleMaintenanceJ1939DiagnosticTroubleCodes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VehicleMaintenance_j1939_diagnosticTroubleCodes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fmi_id' => 'int',
        'fmi_text' => 'string',
        'occurrence_count' => 'int',
        'spn_description' => 'string',
        'spn_id' => 'int',
        'tx_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'fmi_id' => null,
        'fmi_text' => null,
        'occurrence_count' => null,
        'spn_description' => null,
        'spn_id' => null,
        'tx_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fmi_id' => 'fmiId',
        'fmi_text' => 'fmiText',
        'occurrence_count' => 'occurrenceCount',
        'spn_description' => 'spnDescription',
        'spn_id' => 'spnId',
        'tx_id' => 'txId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fmi_id' => 'setFmiId',
        'fmi_text' => 'setFmiText',
        'occurrence_count' => 'setOccurrenceCount',
        'spn_description' => 'setSpnDescription',
        'spn_id' => 'setSpnId',
        'tx_id' => 'setTxId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fmi_id' => 'getFmiId',
        'fmi_text' => 'getFmiText',
        'occurrence_count' => 'getOccurrenceCount',
        'spn_description' => 'getSpnDescription',
        'spn_id' => 'getSpnId',
        'tx_id' => 'getTxId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fmi_id'] = isset($data['fmi_id']) ? $data['fmi_id'] : null;
        $this->container['fmi_text'] = isset($data['fmi_text']) ? $data['fmi_text'] : null;
        $this->container['occurrence_count'] = isset($data['occurrence_count']) ? $data['occurrence_count'] : null;
        $this->container['spn_description'] = isset($data['spn_description']) ? $data['spn_description'] : null;
        $this->container['spn_id'] = isset($data['spn_id']) ? $data['spn_id'] : null;
        $this->container['tx_id'] = isset($data['tx_id']) ? $data['tx_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets fmi_id
     *
     * @return int
     */
    public function getFmiId()
    {
        return $this->container['fmi_id'];
    }

    /**
     * Sets fmi_id
     *
     * @param int $fmi_id fmi_id
     *
     * @return $this
     */
    public function setFmiId($fmi_id)
    {
        $this->container['fmi_id'] = $fmi_id;

        return $this;
    }

    /**
     * Gets fmi_text
     *
     * @return string
     */
    public function getFmiText()
    {
        return $this->container['fmi_text'];
    }

    /**
     * Sets fmi_text
     *
     * @param string $fmi_text fmi_text
     *
     * @return $this
     */
    public function setFmiText($fmi_text)
    {
        $this->container['fmi_text'] = $fmi_text;

        return $this;
    }

    /**
     * Gets occurrence_count
     *
     * @return int
     */
    public function getOccurrenceCount()
    {
        return $this->container['occurrence_count'];
    }

    /**
     * Sets occurrence_count
     *
     * @param int $occurrence_count occurrence_count
     *
     * @return $this
     */
    public function setOccurrenceCount($occurrence_count)
    {
        $this->container['occurrence_count'] = $occurrence_count;

        return $this;
    }

    /**
     * Gets spn_description
     *
     * @return string
     */
    public function getSpnDescription()
    {
        return $this->container['spn_description'];
    }

    /**
     * Sets spn_description
     *
     * @param string $spn_description spn_description
     *
     * @return $this
     */
    public function setSpnDescription($spn_description)
    {
        $this->container['spn_description'] = $spn_description;

        return $this;
    }

    /**
     * Gets spn_id
     *
     * @return int
     */
    public function getSpnId()
    {
        return $this->container['spn_id'];
    }

    /**
     * Sets spn_id
     *
     * @param int $spn_id spn_id
     *
     * @return $this
     */
    public function setSpnId($spn_id)
    {
        $this->container['spn_id'] = $spn_id;

        return $this;
    }

    /**
     * Gets tx_id
     *
     * @return int
     */
    public function getTxId()
    {
        return $this->container['tx_id'];
    }

    /**
     * Sets tx_id
     *
     * @param int $tx_id tx_id
     *
     * @return $this
     */
    public function setTxId($tx_id)
    {
        $this->container['tx_id'] = $tx_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

